# Generated by Django 5.1 on 2024-08-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.ImageField(upload_to='')),
                ('position', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('image', models.TextField(max_length=2000)),
            ],
        ),
    ]
